# Generated by Django 2.1.7 on 2019-11-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20191128_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='zona',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
